name = "paste"
main = "src/index.ts"
compatibility_date = "2023-10-30"

# The default environment is treated as production, this doesn't seem to be changable.
# "preview_bucket_name" is used as the dev bucket with "wrangler dev --remote".
# This particular syntax seems to be necessary when defining additional environments (not shown here).

r2_buckets = [
  { binding = "CONTENT", bucket_name = "paste-content", preview_bucket_name = "paste-content-dev" }
]